version: '3.8'

services:

    database:
        build:
            context: ./database
            dockerfile: Dockerfile
        env_file: .env
        restart: always
        tty: true
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "7331:7331"
        volumes:
            - database_data:/var/lib/postgresql/data

# Volumes
volumes:
    database_data:
